### ISSUE TITLE
Expose SQLErrorStore._tableName through config or allow setting it afterwards

### ISSUE THREAD

**Issue by stijnherreman** [NickCraver/StackExchange.Exceptional#118]
When using `ErrorStoreSettings` via `services.AddExceptional(...)` or `Exceptional.Configure(...)`, the SQL store is created with `"Exceptions"` as table name.

Can you expose store-specific settings through the configuration? If not, can you expose `private readonly string _tableName;` to be set in code afterwards?

I can create a PR if you give some guidelines for how you'd like to see it built.

**Comment by NickCraver** [comment]
Trying to understand the ask here. Setting it in code after wouldn't work because it's denormalized for efficiency (we don't create the query strings every time...just once and memoize). So we need to do it on creation. 

Do you want the table name to be something you can specify from the JSON (or whatever your config source is)? Or am I misunderstanding the request?

**Comment by stijnherreman** [comment]
Yeah, I'd like to specify the table name and the schema name via configuration.

**Comment by NickCraver** [comment]
@stijnherreman git auto-closed this, but packages should be up on MyGet shortly adding `TableName` to the store settings. Example JSON confiig:
```json
{
  "Exceptional": {
    "Store": {
      "ApplicationName": "Samples (ASP.NET Core SQL)",
      "Type": "SQL",
      "ConnectionString": "Server=.;Database=Local.Exceptions;Trusted_Connection=True;",
      "TableName": "MyExceptions"
    }
  }
}
```

**Comment by stijnherreman** [comment]
Thanks, verified that it's working.
