### ISSUE TITLE
Ben.Demystifier integration?

### ISSUE THREAD

**Issue by smurariu2** [NickCraver/StackExchange.Exceptional#119]
Hey guys, 
Would it be an idea to integrate Ben's Demystifier (https://github.com/benaadams/Ben.Demystifier) before we store the exceptions? 
We would save space and also make the stack traces a little easier to understand.

**Comment by NickCraver** [comment]
I'm not sure about the integration *by default* since it up the cost of generating the exception significantly at log time, but I'm working with Ben to optimize it right now and we'll see what happens. 

Regardless of *default* usage, I absolutely agree the plugin should have some way to work, and it should already via:
```c#
ex.Demystify().Log(...);
```

**Comment by smurariu2** [comment]
Got it. I saw on twitter that you were working with ben on it and doing some benchmarking. Just wanted to make sure it's on your radar, so I will close this issue.
