### ISSUE TITLE
rc2.3 and rc2.4 depend on old version of Shared

### ISSUE THREAD

**Issue by stijnherreman** [NickCraver/StackExchange.Exceptional#125]
[StackExchange.Exceptional/2.0.0-rc1-00198](https://www.myget.org/feed/exceptional/package/nuget/StackExchange.Exceptional/2.0.0-rc1-00198) depends on StackExchange.Exceptional.Shared (>= 2.0.0-rc1-00198), but [StackExchange.Exceptional/2.0.0-rc2.3](https://www.myget.org/feed/exceptional/package/nuget/StackExchange.Exceptional/2.0.0-rc2.3) and [StackExchange.Exceptional/2.0.0-rc2.4](https://www.myget.org/feed/exceptional/package/nuget/StackExchange.Exceptional/2.0.0-rc2.4) depend on StackExchange.Exceptional.Shared (>= 1.0.0)

Easily fixed by manually upgrading the Shared package, so not a critical issue.

**Comment by NickCraver** [comment]
I fought with tooling today and we should be all better now. The crux of the issue is https://github.com/NuGet/Home/issues/4337, and it *still* needed a workaround with the latest Appveyor image. For now, we're manually using the 2.1.100-preview-007379 `dotnet` SDK which has fixes in place.

MyGet and NuGet feeds are updated and affected packages have been de-listed. Thanks for the heads up!
