### ISSUE TITLE
ASPNET Core Documentation Updates

### ISSUE THREAD

**Issue by mmillican** [NickCraver/StackExchange.Exceptional#126]
I'll be sending along a PR later this week for this, but wanted to get it documented and possibly open for discussion.  

I noticed a few discrepancies with the docs for getting Exceptional setup in Core, namely with setting up stores and Application name (via code, not config).  More to come, just wanted to note here before I forgot.

**Comment by mmillican** [comment]
Thought I had last night:  creating a page/list of the configurable options.  I realize some of this is in the example `appsettings.json`, but to me its still sometimes helpful to have a list of all the options for quick reference.  Thoughts?  If interested, I'd be happy to put something together.

**Comment by NickCraver** [comment]
@mmillican sorry I didn't see this in email, I'm all for documentation here and it's immensely appreciated.

I have this today: https://nickcraver.com/StackExchange.Exceptional/Settings - which *shounds* like what you're after but could definitely use some improvment (e.g. should we fully qualify each name? - I was torn there because in a lambda that's not use you use the, but maybe some lambda examples up top solves that confusion?)

**Comment by NickCraver** [comment]
I think we've tidied all these - closing out :)

**Comment by mmillican** [comment]
Sorry @NickCraver I apparently missed your reply and this page also. This looks good. I'm pondering possibly trying out a table format, like so:

## Section Heading

Description

| Field | Type | Default | Description |

Thoughts?
