### ISSUE TITLE
 StackExchange.Exceptional does not implement IHttpHandlerFactory or IHttpHandler

### ISSUE THREAD

**Issue by carlosagsmendes** [NickCraver/StackExchange.Exceptional#29]
I was trying the sample MVC app and the Exceptions.axd handler is not working:

Server Error in '/' Application.

StackExchange.Exceptional.ExceptionalModule, StackExchange.Exceptional does not implement IHttpHandlerFactory or IHttpHandler.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Configuration.ConfigurationErrorsException: StackExchange.Exceptional.ExceptionalModule, StackExchange.Exceptional does not implement IHttpHandlerFactory or IHttpHandler.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[ConfigurationErrorsException: StackExchange.Exceptional.ExceptionalModule, StackExchange.Exceptional does not implement IHttpHandlerFactory or IHttpHandler.]
   System.Web.Configuration.HandlerFactoryCache.GetHandlerType(String type) +9657807
   System.Web.Configuration.HandlerFactoryCache..ctor(String type) +19
   System.Web.HttpApplication.GetFactory(String type) +86
   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +262
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18045

**Comment by tmAsim** [comment]
Hi,
It's nice to implement Exceptional to my project. But can you tell me how can i log my handled exceptions in StackExchange's Exceptional? and is there any way to log activities?

**Comment by CptRobby** [comment]
@tmAsim Please don't comment on old tickets for something that's completely unrelated to the ticket. If you need help, create a new ticket.

The way you log handled exceptions is by sending the exception to `ErrorStore.LogException`. It's really simple and is included in the wiki.

As for logging other events that aren't related to exceptions, there really isn't a simple way to do that since everything is based on logging exceptions. However, you could create a new class that inherits `System.Exception` and throw, catch, and log that into Exceptional. Here's an example.
```c#
public static class Logging
{
    private class InfoOnlyException : System.Exception { }

    public static void LogMessage(string message)
    {
        try
        {
            throw new InfoOnlyException(message);
        }
        catch (Exception ex)
        {
            StackExchange.Exceptional.ErrorStore.LogException(ex, HttpContext.Current);
        }
    }
}
```
You would then call `Logging.LogMessage` from your code when you want to add a message into your `ErrorStore`.
