### ISSUE TITLE
MySQLErrorStore in Nuget

### ISSUE THREAD

**Issue by enmik** [NickCraver/StackExchange.Exceptional#56]
I could not find the MySQLErrorStore in the Nuget package StackExchange.Exceptional version 1.0.0.111 (containing StackExchange.Exceptional.dll).

When building the source code my self the MySQLErrorStore seems to be working fine (using StackExchange.Exceptional.dll and StackExchange.Exceptional.MySQL.dll).

Any plans on creating a new Nuget package for MySQLErrorStore (StackExchange.Exceptional.MySQL.dll)? Or include it in the StackExchange.Exceptional package?

**Comment by robdmoore** [comment]
+1

**Comment by NickCraver** [comment]
The reason it isn't currently in NuGet is the performance concern about the rollup. I haven't found the time to test performance, but I know the dupe query hit (and race conditions it creates) are both bad for performance and accuracy - two of the main benefits of a centralized, performant, atomic data store. If someone wants to take the MySQL bits and improve the actual Error saving perf I'd love a pull request - otherwise it has to wait until I find the time to setup a test environment for it. Unfortunately, my scarcest resource is time.

**Comment by martinsteel** [comment]
@NickCraver what are your major performance concerns? The MySQLErrorStore is in production use on a couple of apps and we haven't come across any issues.

**Comment by CptRobby** [comment]
@martinsteel - I'm pretty sure the issues @NickCraver was talking about in his previous comment were the ones mentioned in #49, which appear to have been resolved in #50.

I'm not sure what the status is currently on creating a Nuget package for it, but judging from Nick's previous commit in May, I'm thinking he's probably been busy with other things at StackEx and he's probably got things in a state of flux as he's trying to shift the project into the .Net CoreCLR realm.

Of course, I have no direct knowledge of this, I'm just making educated guesses based on the activity I've seen in this project since I started watching it a few months back. ;)

**Comment by martinsteel** [comment]
@CptRobby if it's just the stuff from #50 that's not a problem. I was only asking as the comment was much more recent than that pull request.

**Comment by CptRobby** [comment]
@martinsteel Look at the time stamps. PR #50 wasn't accepted until 10 minutes after his previous comment here. And his last comment in #50 mentioned that it was why he was holding off on including it in the NuGet. ;)

**Comment by NickCraver** [comment]
Sorry guys, busy is a bit of an understatement these days - but I didn't want to let this one sit until I have time to figure out the CoreCLR port (the combined nature is currently fundamentally incompatible).

I've updated NuGet to the latest here: 
https://www.nuget.org/packages/StackExchange.Exceptional/
And I've pushed up the MySQL package here:
https://www.nuget.org/packages/StackExchange.Exceptional.MySQL

If someone can please confirm it works okay on their setup, I'll close this out. Thanks again!
