### ISSUE TITLE
JSON store path configuration problem

### ISSUE THREAD

**Issue by DejanMilicic** [NickCraver/StackExchange.Exceptional#67]
I decided to go with JSON Error store. Configuration via web.config. Exceptional kept translating path="~/Errors" as being relative not to application but relative to web server. I am using IIS Express 8.5 on my project.
I solved this by switching to code-based configuration. Same path "~/Errors" was correctly mapped this time.

**Comment by CptRobby** [comment]
Try "~\Errors", with a backslash instead of a forward slash.

The `JSONErrorStore` constructor calls the `ResolvePath` extension method defined in ExtensionMethods.cs, which replaces "~\" with `AppDomain.CurrentDomain.GetData("APPBASE")`, which I'm assuming is the path to the directory containing your website.

**Comment by NickCraver** [comment]
Covered above - closing out to cleanup.
